I want to do a varaiety of extractions of cliamte data from ERA5 so that I can get climate normals, and long time series. I am hoping dask can make is less paiful. I am following the examples here: https://projectpythia.org/ERA5_interactive-cookbook/

In [1]:
import glob
import re
import matplotlib as plt
import numpy as np
import scipy as sp
import xarray as xr
import intake
import intake_esm
import pandas as pd

/srv/conda/envs/notebook/lib/python3.12/site-packages/intake_esm/__init__.py:6: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import DistributionNotFound, get_distribution

In [3]:
! pip install dask_jobqueue

Collecting dask_jobqueue
  Downloading dask_jobqueue-0.9.0-py2.py3-none-any.whl.metadata (1.3 kB)
Requirement already satisfied: dask>=2022.02.0 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from dask_jobqueue) (2025.12.0)
Requirement already satisfied: distributed>=2022.02.0 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from dask_jobqueue) (2025.12.0)
Requirement already satisfied: click>=8.1 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from dask>=2022.02.0->dask_jobqueue) (8.3.1)
Requirement already satisfied: cloudpickle>=3.0.0 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from dask>=2022.02.0->dask_jobqueue) (3.1.2)
Requirement already satisfied: fsspec>=2021.09.0 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from dask>=2022.02.0->dask_jobqueue) (2025.12.0)
Requirement already satisfied: packaging>=20.0 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from dask>=2022.02.0->dask_jobqueue) (25.0)
Requirement already satisfied: partd>=1.4.0 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from dask>=2022.02.0->dask_jobqueue) (1.4.2)
Requirement already satisfied: pyyaml>=5.3.1 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from dask>=2022.02.0->dask_jobqueue) (6.0.3)
Requirement already satisfied: toolz>=0.12.0 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from dask>=2022.02.0->dask_jobqueue) (1.1.0)
Requirement already satisfied: jinja2>=2.10.3 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from distributed>=2022.02.0->dask_jobqueue) (3.1.6)
Requirement already satisfied: locket>=1.0.0 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from distributed>=2022.02.0->dask_jobqueue) (1.0.0)
Requirement already satisfied: msgpack>=1.0.2 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from distributed>=2022.02.0->dask_jobqueue) (1.1.2)
Requirement already satisfied: psutil>=5.8.0 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from distributed>=2022.02.0->dask_jobqueue) (7.2.1)
Requirement already satisfied: sortedcontainers>=2.0.5 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from distributed>=2022.02.0->dask_jobqueue) (2.4.0)
Requirement already satisfied: tblib!=3.2.0,!=3.2.1,>=1.6.0 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from distributed>=2022.02.0->dask_jobqueue) (3.2.2)
Requirement already satisfied: tornado>=6.2.0 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from distributed>=2022.02.0->dask_jobqueue) (6.5.3)
Requirement already satisfied: urllib3>=1.26.5 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from distributed>=2022.02.0->dask_jobqueue) (1.26.20)
Requirement already satisfied: zict>=3.0.0 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from distributed>=2022.02.0->dask_jobqueue) (3.0.0)
Requirement already satisfied: MarkupSafe>=2.0 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from jinja2>=2.10.3->distributed>=2022.02.0->dask_jobqueue) (3.0.3)
Downloading dask_jobqueue-0.9.0-py2.py3-none-any.whl (52 kB)
Installing collected packages: dask_jobqueue
Successfully installed dask_jobqueue-0.9.0

In [4]:
import dask
from dask.distributed import Client, performance_report,LocalCluster
from dask_jobqueue import PBSCluster

In [5]:
######## File paths ################
gdex_scratch   = "/lustre/desc1/scratch/harshah"
era5_catalog = 'https://data.gdex.ucar.edu/special_projects/pythia_2024/pythia_intake_catalogs/era5_catalog.json'
#annual_means      = '/gdex/data/special_projects/pythia_2024/annual_means/' #Posix path, only used for writing data 
annual_means_https= 'https://data.gdex.ucar.edu/special_projects/pythia_2024/annual_means/'

print(era5_catalog)

https://data.gdex.ucar.edu/special_projects/pythia_2024/pythia_intake_catalogs/era5_catalog.json

In [ ]:
USE_PBS_SCHEDULER = False

USE_DASK_GATEWAY = True # I think Dask gateway is enabled on Veda

In [6]:
def get_gateway_cluster():
    """ Create cluster through dask_gateway
    """
    from dask_gateway import Gateway

    gateway = Gateway()
    cluster = gateway.new_cluster()
    cluster.adapt(minimum=2, maximum=4)
    return cluster

In [8]:
# Connect to 

cluster = get_gateway_cluster()
from distributed import Client
client = Client(cluster)

2026-03-10 16:44:11,118 - distributed.client - ERROR - Failed to reconnect to scheduler after 30.00 seconds, closing client

In [9]:
cluster

VBox(children=(HTML(value='<h2>GatewayCluster</h2>'), HBox(children=(HTML(value='\n<div>\n<style scoped>\n    …

In [10]:
era5_cat = intake.open_esm_datastore(era5_catalog)
era5_cat

/srv/conda/envs/notebook/lib/python3.12/site-packages/intake_esm/cat.py:251: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(

In [13]:
#era5_cat.df[['long_name','variable', 'units']].drop_duplicates().head()

                       long_name variable                units
0            Potential vorticity       PV  K m**2 kg**-1 s**-1
31   Specific rain water content     CRWC            kg kg**-1
62   Specific snow water content     CSWC            kg kg**-1
93                  Geopotential        Z           m**2 s**-2
124                  Temperature        T                    K

Exception in callback None()
handle: <Handle cancelled>
Traceback (most recent call last):
  File "/srv/conda/envs/notebook/lib/python3.12/site-packages/tornado/iostream.py", line 1363, in _do_ssl_handshake
    self.socket.do_handshake()
  File "/srv/conda/envs/notebook/lib/python3.12/ssl.py", line 1319, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1010)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/conda/envs/notebook/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/srv/conda/envs/notebook/lib/python3.12/site-packages/tornado/platform/asyncio.py", line 208, in _handle_events
    handler_func(fileobj, events)
  File "/srv/conda/envs/notebook/lib/python3.12/site-packages/tornado/iostream.py", line 691, in _handle_events
    self._handle_read()
  File "/srv/conda/envs/notebook/lib/python3.12/site-packages/tornado/iostream.py", line 1417, in _handle_read
    self._do_ssl_handshake()
  File "/srv/conda/envs/notebook/lib/python3.12/site-packages/tornado/iostream.py", line 1381, in _do_ssl_handshake
    return self.close(exc_info=err)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/conda/envs/notebook/lib/python3.12/site-packages/tornado/iostream.py", line 606, in close
    self._signal_closed()
  File "/srv/conda/envs/notebook/lib/python3.12/site-packages/tornado/iostream.py", line 636, in _signal_closed
    self._ssl_connect_future.exception()
asyncio.exceptions.CancelledError

# This seems like it's only for specific pre-generated tempurature data from this one place. Now I am referencing this: 
https://era-explorer.climate.copernicus.eu/notebooks/content/precipitation/precip_monthly_climatology.html

In [15]:
! pip install earthkit.data

Collecting earthkit.data
  Downloading earthkit_data-0.19.1-py3-none-any.whl.metadata (7.6 kB)
Requirement already satisfied: cfgrib>=0.9.10.1 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from earthkit.data) (0.9.15.1)
Requirement already satisfied: dask in /srv/conda/envs/notebook/lib/python3.12/site-packages (from earthkit.data) (2025.12.0)
Collecting deprecation (from earthkit.data)
  Downloading deprecation-2.1.0-py2.py3-none-any.whl.metadata (4.6 kB)
Collecting earthkit-meteo>=0.6 (from earthkit.data)
  Downloading earthkit_meteo-0.6.1-py3-none-any.whl.metadata (4.8 kB)
Collecting earthkit-utils>=0.2 (from earthkit.data)
  Downloading earthkit_utils-0.2.1-py3-none-any.whl.metadata (4.2 kB)
Requirement already satisfied: eccodes>=1.7 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from earthkit.data) (2.44.0)
Collecting entrypoints (from earthkit.data)
  Downloading entrypoints-0.4-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: filelock in /srv/conda/envs/notebook/lib/python3.12/site-packages (from earthkit.data) (3.20.1)
Requirement already satisfied: jinja2 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from earthkit.data) (3.1.6)
Requirement already satisfied: jsonschema in /srv/conda/envs/notebook/lib/python3.12/site-packages (from earthkit.data) (4.25.1)
Collecting lru-dict (from earthkit.data)
  Downloading lru_dict-1.4.1-cp312-cp312-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl.metadata (4.8 kB)
Requirement already satisfied: markdown in /srv/conda/envs/notebook/lib/python3.12/site-packages (from earthkit.data) (3.10)
Requirement already satisfied: multiurl>=0.3.3 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from earthkit.data) (0.3.7)
Requirement already satisfied: netcdf4 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from earthkit.data) (1.7.3)
Requirement already satisfied: pandas in /srv/conda/envs/notebook/lib/python3.12/site-packages (from earthkit.data) (2.3.3)
Collecting pdbufr>=0.11 (from earthkit.data)
  Downloading pdbufr-0.14.2-py3-none-any.whl.metadata (3.1 kB)
Requirement already satisfied: pyyaml in /srv/conda/envs/notebook/lib/python3.12/site-packages (from earthkit.data) (6.0.3)
Requirement already satisfied: tqdm>=4.63 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from earthkit.data) (4.67.1)
Requirement already satisfied: xarray>=0.19 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from earthkit.data) (2025.12.0)
Requirement already satisfied: attrs>=19.2 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from cfgrib>=0.9.10.1->earthkit.data) (25.4.0)
Requirement already satisfied: click in /srv/conda/envs/notebook/lib/python3.12/site-packages (from cfgrib>=0.9.10.1->earthkit.data) (8.3.1)
Requirement already satisfied: numpy in /srv/conda/envs/notebook/lib/python3.12/site-packages (from cfgrib>=0.9.10.1->earthkit.data) (2.3.5)
Collecting array-api-compat (from earthkit-utils>=0.2->earthkit.data)
  Downloading array_api_compat-1.14.0-py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: cffi in /srv/conda/envs/notebook/lib/python3.12/site-packages (from eccodes>=1.7->earthkit.data) (2.0.0)
Requirement already satisfied: findlibs in /srv/conda/envs/notebook/lib/python3.12/site-packages (from eccodes>=1.7->earthkit.data) (0.1.2)
Requirement already satisfied: requests in /srv/conda/envs/notebook/lib/python3.12/site-packages (from multiurl>=0.3.3->earthkit.data) (2.32.5)
Requirement already satisfied: pytz in /srv/conda/envs/notebook/lib/python3.12/site-packages (from multiurl>=0.3.3->earthkit.data) (2025.2)
Requirement already satisfied: python-dateutil in /srv/conda/envs/notebook/lib/python3.12/site-packages (from multiurl>=0.3.3->earthkit.data) (2.9.0)
Requirement already satisfied: pint in /srv/conda/envs/notebook/lib/python3.12/site-packages (from pdbufr>=0.11->earthkit.data) (0.25.2)
Requirement already satisfied: packaging>=24.1 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from xarray>=0.19->earthkit.data) (25.0)
Requirement already satisfied: tzdata>=2022.7 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from pandas->earthkit.data) (2025.3)
Requirement already satisfied: six>=1.5 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from python-dateutil->multiurl>=0.3.3->earthkit.data) (1.17.0)
Requirement already satisfied: pycparser in /srv/conda/envs/notebook/lib/python3.12/site-packages (from cffi->eccodes>=1.7->earthkit.data) (2.22)
Requirement already satisfied: cloudpickle>=3.0.0 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from dask->earthkit.data) (3.1.2)
Requirement already satisfied: fsspec>=2021.09.0 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from dask->earthkit.data) (2025.12.0)
Requirement already satisfied: partd>=1.4.0 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from dask->earthkit.data) (1.4.2)
Requirement already satisfied: toolz>=0.12.0 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from dask->earthkit.data) (1.1.0)
Requirement already satisfied: locket in /srv/conda/envs/notebook/lib/python3.12/site-packages (from partd>=1.4.0->dask->earthkit.data) (1.0.0)
Requirement already satisfied: MarkupSafe>=2.0 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from jinja2->earthkit.data) (3.0.3)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from jsonschema->earthkit.data) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from jsonschema->earthkit.data) (0.37.0)
Requirement already satisfied: rpds-py>=0.7.1 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from jsonschema->earthkit.data) (0.30.0)
Requirement already satisfied: typing-extensions>=4.4.0 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from referencing>=0.28.4->jsonschema->earthkit.data) (4.15.0)
Requirement already satisfied: cftime in /srv/conda/envs/notebook/lib/python3.12/site-packages (from netcdf4->earthkit.data) (1.6.4)
Requirement already satisfied: certifi in /srv/conda/envs/notebook/lib/python3.12/site-packages (from netcdf4->earthkit.data) (2026.1.4)
Requirement already satisfied: flexcache>=0.3 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from pint->pdbufr>=0.11->earthkit.data) (0.3)
Requirement already satisfied: flexparser>=0.4 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from pint->pdbufr>=0.11->earthkit.data) (0.4)
Requirement already satisfied: platformdirs>=2.1.0 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from pint->pdbufr>=0.11->earthkit.data) (4.5.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from requests->multiurl>=0.3.3->earthkit.data) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from requests->multiurl>=0.3.3->earthkit.data) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /srv/conda/envs/notebook/lib/python3.12/site-packages (from requests->multiurl>=0.3.3->earthkit.data) (1.26.20)
Downloading earthkit_data-0.19.1-py3-none-any.whl (395 kB)
Downloading earthkit_meteo-0.6.1-py3-none-any.whl (57 kB)
Downloading earthkit_utils-0.2.1-py3-none-any.whl (25 kB)
Downloading pdbufr-0.14.2-py3-none-any.whl (52 kB)
Downloading array_api_compat-1.14.0-py3-none-any.whl (60 kB)
Downloading deprecation-2.1.0-py2.py3-none-any.whl (11 kB)
Downloading entrypoints-0.4-py3-none-any.whl (5.3 kB)
Downloading lru_dict-1.4.1-cp312-cp312-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl (31 kB)
Installing collected packages: lru-dict, entrypoints, deprecation, array-api-compat, earthkit-utils, earthkit-meteo, pdbufr, earthkit.data
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8/8 [earthkit.data]0m [earthkit.data]
Successfully installed array-api-compat-1.14.0 deprecation-2.1.0 earthkit-meteo-0.6.1 earthkit-utils-0.2.1 earthkit.data-0.19.1 entrypoints-0.4 lru-dict-1.4.1 pdbufr-0.14.2

In [16]:
import pandas as pd
import matplotlib.pyplot as plt
import calendar
import earthkit.data

In [17]:
## per lat lon 
lat = 50.86
lng = 4.

variable = "total_precipitation"
date_range = ["1991-01-01", "2020-12-31"]

In [18]:
def retrieve_data(variable, date_range, lat, lng):
    # Define the dataset and request parameters
    dataset = "reanalysis-era5-single-levels-timeseries"
    request = {
        "variable": [
        variable,  # Variable to retrieve
        ],
        "date": date_range,  # Date range for the data
        "location": {"longitude": lng, "latitude": lat},  # Location coordinates
        "data_format": "netcdf"  # Format of the retrieved data
    }

    # Use "earthkit" to retrieve the data
    ekds = earthkit.data.from_source(
        "cds", dataset, request
    ).to_xarray()

    return ekds

In [19]:
data = retrieve_data(variable, date_range, lat, lng)

2026-03-10 18:07:14,179 INFO [2026-02-16T00:00:00] - To generate this ERA5 hourly time series dataset, **homogenisation conventions have been applied to the ERA5 source GRIB data** to ensure consistency, usability, and alignment across chosen variables and time steps. The processed data were then written to an **ARCO Zarr archive**, enabling efficient cloud-optimised access and scalable data retrieval. Please refer to the [user guide](https://confluence.ecmwf.int/x/R6cfHg) for details.

- The dataset presented here is a subset of selected parameters from the full [CDS ERA5 hourly data on single levels (1940–present)](https://cds.climate.copernicus.eu/datasets/reanalysis-era5-single-levels?tab=overview). **Requirements for additional parameters may be considered**. Please raise your request with ECMWF Support [here](https://jira.ecmwf.int/plugins/servlet/desk/portal/1/create/202).
2026-03-10 18:07:14,180 INFO Request ID is 8c35b342-0a5a-4347-87f8-43ed6f28b7eb
2026-03-10 18:07:14,391 INFO status has been updated to accepted
2026-03-10 18:07:23,372 INFO status has been updated to running
2026-03-10 18:07:28,652 INFO status has been updated to successful

f98f7ee7994a8e71402be3ec8a6f5e64.zip:   0%|          | 0.00/3.02M [00:00<?, ?B/s]

  0%|          | 0/1 [00:00<?, ?it/s]

In [30]:
# Make a function to compute the monthly precipitation climatology
def precipMonthlyClimatology():
    """
    Calculate the monthly climatology of precipitation.

    This function reads precipitation data from a NetCDF file,
    converts the time coordinate to a pandas datetime index,
    and then resamples the data to calculate the monthly 
    climatology. The resulting climatology is returned in millimeters.

    Returns:
        pandas.DataFrame: A DataFrame containing the monthly climatology
        of precipitation in millimeters, indexed by month.
    """


    data_tp_pt = data.tp

    # Convert the time coordinate to a pandas datetime index
    time_index = pd.to_datetime(data_tp_pt.valid_time.values)

    # Create a DataFrame for easier manipulation
    df = pd.DataFrame(data_tp_pt.values, index=time_index, columns=['tp'])

    df_monthly = df.resample('d').sum()
    df_monthly['month_day'] = df_monthly.index.month.astype("str") + "_" + df_monthly.index.day.astype("str")
    monthly_climatology = df_monthly.groupby('month_day').mean() * 1000

    # Get the actual lat/lon used
    nearest_lat = data_tp_pt.latitude.values
    nearest_lng = data_tp_pt.longitude.values

    return monthly_climatology, nearest_lat, nearest_lng


# Call our function
clim, nearest_lat, nearest_lng = precipMonthlyClimatology()